// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "dt_ias.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

NSObject<FlutterMessageCodec> *DTDTIasPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void SetUpDTDTIasPigeon(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTIasPigeon> *api) {
  SetUpDTDTIasPigeonWithSuffix(binaryMessenger, api, @"");
}

void SetUpDTDTIasPigeonWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTIasPigeon> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.datatower_ai_core.DTIasPigeon.reportSubscribeSuccessAndroid", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:DTDTIasPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportSubscribeSuccessAndroidOriginalOrderId:orderId:sku:price:currency:properties:error:)], @"DTDTIasPigeon api (%@) doesn't respond to @selector(reportSubscribeSuccessAndroidOriginalOrderId:orderId:sku:price:currency:properties:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_originalOrderId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_orderId = GetNullableObjectAtIndex(args, 1);
        NSString *arg_sku = GetNullableObjectAtIndex(args, 2);
        double arg_price = [GetNullableObjectAtIndex(args, 3) doubleValue];
        NSString *arg_currency = GetNullableObjectAtIndex(args, 4);
        NSDictionary<NSString *, id> *arg_properties = GetNullableObjectAtIndex(args, 5);
        FlutterError *error;
        [api reportSubscribeSuccessAndroidOriginalOrderId:arg_originalOrderId orderId:arg_orderId sku:arg_sku price:arg_price currency:arg_currency properties:arg_properties error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.datatower_ai_core.DTIasPigeon.reportSubscribeSuccessIos", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:DTDTIasPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportSubscribeSuccessIosSeq:placement:sku:orderId:originalOrderId:price:currency:entrance:error:)], @"DTDTIasPigeon api (%@) doesn't respond to @selector(reportSubscribeSuccessIosSeq:placement:sku:orderId:originalOrderId:price:currency:entrance:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_seq = GetNullableObjectAtIndex(args, 0);
        NSString *arg_placement = GetNullableObjectAtIndex(args, 1);
        NSString *arg_sku = GetNullableObjectAtIndex(args, 2);
        NSString *arg_orderId = GetNullableObjectAtIndex(args, 3);
        NSString *arg_originalOrderId = GetNullableObjectAtIndex(args, 4);
        NSString *arg_price = GetNullableObjectAtIndex(args, 5);
        NSString *arg_currency = GetNullableObjectAtIndex(args, 6);
        NSString *arg_entrance = GetNullableObjectAtIndex(args, 7);
        FlutterError *error;
        [api reportSubscribeSuccessIosSeq:arg_seq placement:arg_placement sku:arg_sku orderId:arg_orderId originalOrderId:arg_originalOrderId price:arg_price currency:arg_currency entrance:arg_entrance error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
