// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by DTDTIapPigeon.
NSObject<FlutterMessageCodec> *DTDTIapPigeonGetCodec(void);

@protocol DTDTIapPigeon
- (void)reportPurchaseSuccessAndroidOrder:(NSString *)order sku:(NSString *)sku price:(double)price currency:(NSString *)currency properties:(NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportPurchaseSuccessIosOrder:(NSString *)order sku:(NSString *)sku price:(double)price currency:(NSString *)currency seq:(NSString *)seq entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpDTDTIapPigeon(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTIapPigeon> *_Nullable api);

extern void SetUpDTDTIapPigeonWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTIapPigeon> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
