// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by DTDTIasPigeon.
NSObject<FlutterMessageCodec> *DTDTIasPigeonGetCodec(void);

@protocol DTDTIasPigeon
- (void)reportSubscribeSuccessAndroidOriginalOrderId:(NSString *)originalOrderId orderId:(NSString *)orderId sku:(NSString *)sku price:(double)price currency:(NSString *)currency properties:(NSDictionary<NSString *, id> *)properties error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportSubscribeSuccessIosSeq:(NSString *)seq placement:(NSString *)placement sku:(NSString *)sku orderId:(NSString *)orderId originalOrderId:(NSString *)originalOrderId price:(NSString *)price currency:(NSString *)currency entrance:(NSString *)entrance error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpDTDTIasPigeon(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTIasPigeon> *_Nullable api);

extern void SetUpDTDTIasPigeonWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DTDTIasPigeon> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
